name: Continuous integration

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16

      - run: yarn build

      - run: yarn test
